// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CK_TRANSPORT_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CK_TRANSPORT_METHOD0
typedef void (*UniffiCallbackInterfaceCkTransportMethod0)(uint64_t, RustBuffer, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFutureDroppedCallbackStruct* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CK_TRANSPORT
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CK_TRANSPORT
typedef struct UniffiVTableCallbackInterfaceCkTransport {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceCkTransportMethod0 _Nonnull transmitApdu;
} UniffiVTableCallbackInterfaceCkTransport;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_SATSCARD
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_SATSCARD
uint64_t uniffi_cktap_ffi_fn_clone_satscard(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_SATSCARD
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_SATSCARD
void uniffi_cktap_ffi_fn_free_satscard(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_ADDRESS
uint64_t uniffi_cktap_ffi_fn_method_satscard_address(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_CHECK_CERT
uint64_t uniffi_cktap_ffi_fn_method_satscard_check_cert(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_DUMP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_DUMP
uint64_t uniffi_cktap_ffi_fn_method_satscard_dump(uint64_t ptr, uint8_t slot, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_NEW_SLOT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_NEW_SLOT
uint64_t uniffi_cktap_ffi_fn_method_satscard_new_slot(uint64_t ptr, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_NFC
uint64_t uniffi_cktap_ffi_fn_method_satscard_nfc(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_READ
uint64_t uniffi_cktap_ffi_fn_method_satscard_read(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_SIGN_PSBT
uint64_t uniffi_cktap_ffi_fn_method_satscard_sign_psbt(uint64_t ptr, uint8_t slot, RustBuffer psbt, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_STATUS
uint64_t uniffi_cktap_ffi_fn_method_satscard_status(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_UNSEAL
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_UNSEAL
uint64_t uniffi_cktap_ffi_fn_method_satscard_unseal(uint64_t ptr, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCARD_WAIT
uint64_t uniffi_cktap_ffi_fn_method_satscard_wait(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_SATSCHIP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_SATSCHIP
uint64_t uniffi_cktap_ffi_fn_clone_satschip(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_SATSCHIP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_SATSCHIP
void uniffi_cktap_ffi_fn_free_satschip(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_CHANGE
uint64_t uniffi_cktap_ffi_fn_method_satschip_change(uint64_t ptr, RustBuffer new_cvc, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_CHECK_CERT
uint64_t uniffi_cktap_ffi_fn_method_satschip_check_cert(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_DERIVE
uint64_t uniffi_cktap_ffi_fn_method_satschip_derive(uint64_t ptr, RustBuffer path, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_INIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_INIT
uint64_t uniffi_cktap_ffi_fn_method_satschip_init(uint64_t ptr, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_NFC
uint64_t uniffi_cktap_ffi_fn_method_satschip_nfc(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_READ
uint64_t uniffi_cktap_ffi_fn_method_satschip_read(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_SIGN_PSBT
uint64_t uniffi_cktap_ffi_fn_method_satschip_sign_psbt(uint64_t ptr, RustBuffer psbt, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_STATUS
uint64_t uniffi_cktap_ffi_fn_method_satschip_status(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_WAIT
uint64_t uniffi_cktap_ffi_fn_method_satschip_wait(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_XPUB
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_SATSCHIP_XPUB
uint64_t uniffi_cktap_ffi_fn_method_satschip_xpub(uint64_t ptr, int8_t master, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_TAPSIGNER
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_CLONE_TAPSIGNER
uint64_t uniffi_cktap_ffi_fn_clone_tapsigner(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_TAPSIGNER
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FREE_TAPSIGNER
void uniffi_cktap_ffi_fn_free_tapsigner(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_CHANGE
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_change(uint64_t ptr, RustBuffer new_cvc, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_CHECK_CERT
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_check_cert(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_DERIVE
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_derive(uint64_t ptr, RustBuffer path, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_INIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_INIT
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_init(uint64_t ptr, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_NFC
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_nfc(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_READ
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_read(uint64_t ptr, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_SIGN_DIGEST
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_SIGN_DIGEST
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_sign_digest(uint64_t ptr, RustBuffer digest, RustBuffer sub_path, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_SIGN_PSBT
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_sign_psbt(uint64_t ptr, RustBuffer psbt, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_STATUS
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_status(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_WAIT
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_wait(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_XPUB
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_METHOD_TAPSIGNER_XPUB
uint64_t uniffi_cktap_ffi_fn_method_tapsigner_xpub(uint64_t ptr, int8_t master, RustBuffer cvc
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_INIT_CALLBACK_VTABLE_CKTRANSPORT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_INIT_CALLBACK_VTABLE_CKTRANSPORT
void uniffi_cktap_ffi_fn_init_callback_vtable_cktransport(const UniffiVTableCallbackInterfaceCkTransport* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FUNC_TO_CKTAP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_FN_FUNC_TO_CKTAP
uint64_t uniffi_cktap_ffi_fn_func_to_cktap(uint64_t transport
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_cktap_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_cktap_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_FREE
void ffi_cktap_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_cktap_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U8
void ffi_cktap_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U8
void ffi_cktap_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U8
void ffi_cktap_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_cktap_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I8
void ffi_cktap_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I8
void ffi_cktap_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I8
void ffi_cktap_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_cktap_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U16
void ffi_cktap_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U16
void ffi_cktap_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U16
void ffi_cktap_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_cktap_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I16
void ffi_cktap_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I16
void ffi_cktap_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I16
void ffi_cktap_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_cktap_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U32
void ffi_cktap_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U32
void ffi_cktap_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U32
void ffi_cktap_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_cktap_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I32
void ffi_cktap_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I32
void ffi_cktap_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I32
void ffi_cktap_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_cktap_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_U64
void ffi_cktap_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_U64
void ffi_cktap_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_U64
void ffi_cktap_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_cktap_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_I64
void ffi_cktap_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_I64
void ffi_cktap_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_I64
void ffi_cktap_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_cktap_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_F32
void ffi_cktap_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_F32
void ffi_cktap_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_F32
void ffi_cktap_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_cktap_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_F64
void ffi_cktap_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_F64
void ffi_cktap_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_F64
void ffi_cktap_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_cktap_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_cktap_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_cktap_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_cktap_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_cktap_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_POLL_VOID
void ffi_cktap_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_cktap_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_FREE_VOID
void ffi_cktap_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_cktap_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_FUNC_TO_CKTAP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_FUNC_TO_CKTAP
uint16_t uniffi_cktap_ffi_checksum_func_to_cktap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_ADDRESS
uint16_t uniffi_cktap_ffi_checksum_method_satscard_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_CHECK_CERT
uint16_t uniffi_cktap_ffi_checksum_method_satscard_check_cert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_DUMP
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_DUMP
uint16_t uniffi_cktap_ffi_checksum_method_satscard_dump(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_NEW_SLOT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_NEW_SLOT
uint16_t uniffi_cktap_ffi_checksum_method_satscard_new_slot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_NFC
uint16_t uniffi_cktap_ffi_checksum_method_satscard_nfc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_READ
uint16_t uniffi_cktap_ffi_checksum_method_satscard_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_SIGN_PSBT
uint16_t uniffi_cktap_ffi_checksum_method_satscard_sign_psbt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_STATUS
uint16_t uniffi_cktap_ffi_checksum_method_satscard_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_UNSEAL
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_UNSEAL
uint16_t uniffi_cktap_ffi_checksum_method_satscard_unseal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCARD_WAIT
uint16_t uniffi_cktap_ffi_checksum_method_satscard_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_CHANGE
uint16_t uniffi_cktap_ffi_checksum_method_satschip_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_CHECK_CERT
uint16_t uniffi_cktap_ffi_checksum_method_satschip_check_cert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_DERIVE
uint16_t uniffi_cktap_ffi_checksum_method_satschip_derive(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_INIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_INIT
uint16_t uniffi_cktap_ffi_checksum_method_satschip_init(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_NFC
uint16_t uniffi_cktap_ffi_checksum_method_satschip_nfc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_READ
uint16_t uniffi_cktap_ffi_checksum_method_satschip_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_SIGN_PSBT
uint16_t uniffi_cktap_ffi_checksum_method_satschip_sign_psbt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_STATUS
uint16_t uniffi_cktap_ffi_checksum_method_satschip_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_WAIT
uint16_t uniffi_cktap_ffi_checksum_method_satschip_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_XPUB
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_SATSCHIP_XPUB
uint16_t uniffi_cktap_ffi_checksum_method_satschip_xpub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_CHANGE
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_CHECK_CERT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_CHECK_CERT
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_check_cert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_DERIVE
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_derive(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_INIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_INIT
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_init(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_NFC
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_NFC
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_nfc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_READ
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_READ
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_SIGN_DIGEST
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_SIGN_DIGEST
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_sign_digest(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_SIGN_PSBT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_SIGN_PSBT
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_sign_psbt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_STATUS
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_WAIT
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_WAIT
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_XPUB
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_TAPSIGNER_XPUB
uint16_t uniffi_cktap_ffi_checksum_method_tapsigner_xpub(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_CKTRANSPORT_TRANSMIT_APDU
#define UNIFFI_FFIDEF_UNIFFI_CKTAP_FFI_CHECKSUM_METHOD_CKTRANSPORT_TRANSMIT_APDU
uint16_t uniffi_cktap_ffi_checksum_method_cktransport_transmit_apdu(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CKTAP_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CKTAP_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_cktap_ffi_uniffi_contract_version(void
    
);
#endif

